### ISSUE TITLE
xss代理页面提示“invalid server”

### ISSUE THREAD

**Issue by killmonday** [Yeuoly/FxxkXSS#1]
这种代理方式是不是失效了？

![image](https://user-images.githubusercontent.com/59520081/134714233-f17da940-5472-4959-a169-21a80d784966.png)

**Comment by Yeuoly** [comment]
这种情况是说明代理服务器没有找到指定的session，比如说你这里是s2，也就是第三个被xss的浏览器，在被xss得浏览器关闭之后或者压根就没有这个浏览器的情况下就是invaild server的提示
